apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: okteto.dev/main:latest
        name: main
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "b102385b-ea81-4a3d-ae73-977d1d261d63"
        - name: Vless_Path
          value: "/vhdg77Lfd"
        - name: Vmess_UUID
          value: "b102385b-ea81-4a3d-ae73-977d1d261d63"
        - name: Vmess_Path
          value: "/vyds78Mjg"
        - name: Share_Path
          value: "$Share_Path"
