apiVersion: apps/v1
kind: Deployment
metadata:
  name: sad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sad
  template:
    metadata:
      labels:
        app: sad
    spec:
      containers:
      - image: okteto.dev/sad:latest
        name: sad
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1899232b-441d-47c8-bf45-ef53a2327d99"
        - name: Vless_Path
          value: "/vhdg77Lfd"
        - name: Vmess_UUID
          value: "1899232b-441d-47c8-bf45-ef53a2327d99"
        - name: Vmess_Path
          value: "/vyds78Mjg"
        - name: Share_Path
          value: "$Share_Path"
